function firstScreen () {
    scene.setBackgroundColor(6)
    Vulture = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ........3333....................
        ....fddd3fd3....................
        ....fff33333ff..................
        .........33311ff................
        .........f3111fffff.............
        ........f11111fffff.............
        ........f1111fffffff............
        ........fffffffffffff...........
        .......fffffffffffffffff........
        .......fffffffbbfffffffff.......
        ......ffbbffffffbbbffffff.......
        ......fffbbfffffffbbffff........
        .......ffffbfffffffbbfff........
        .......ffffbbfffffffbff.........
        ........ffffbbfffffffff.........
        .........ffffbbffffffff.........
        ..........ffffbbfffff...........
        ..........ffffffffffff..........
        ............fffffffbfff.........
        ............4ffffffbbff.........
        ............44ffffffbfff........
        ............44.4f.fff.f.........
        ............44.44..ff.f.........
        ...........444.444.f............
        ................................
        ................................
        ................................
        `, SpriteKind.Player)
    Vulture.setPosition(17, 89)
    Monkey = sprites.create(img`
        . . . . f f f f f . . . . . . . 
        . . . f e e e e e f . . . . . . 
        . . f d d d d e e e f . . . . . 
        . c d f d d f d e e f f . . . . 
        . c d f d d f d e e d d f . . . 
        c d e e d d d d e e b d c . . . 
        c d d d d c d d e e b d c . f f 
        c c c c c d d d e e f c . f e f 
        . f d d d d d e e f f . . f e f 
        . . f f f f f e e e e f . f e f 
        . . . . f e e e e e e e f f e f 
        . . . f e f f e f e e e e f f . 
        . . . f e f f e f e e e e f . . 
        . . . f d b f d b f f e f . . . 
        . . . f d d c d d b b d f . . . 
        . . . . f f f f f f f f f . . . 
        `, SpriteKind.Player)
    Monkey.setPosition(37, 73)
    Duck = sprites.create(img`
        . . . . . . . . . . b 5 b . . . 
        . . . . . . . . . b 5 b . . . . 
        . . . . . . b b b b b b . . . . 
        . . . . . b b 5 5 5 5 5 b . . . 
        . . . . b b 5 d 1 f 5 d 4 c . . 
        . . . . b 5 5 1 f f d d 4 4 4 b 
        . . . . b 5 5 d f b 4 4 4 4 b . 
        . . . b d 5 5 5 5 4 4 4 4 b . . 
        . b b d d d 5 5 5 5 5 5 5 b . . 
        b d d d b b b 5 5 5 5 5 5 5 b . 
        c d d b 5 5 d c 5 5 5 5 5 5 b . 
        c b b d 5 d c d 5 5 5 5 5 5 b . 
        c b 5 5 b c d d 5 5 5 5 5 5 b . 
        b b c c c d d d 5 5 5 5 5 d b . 
        . . . . c c d d d 5 5 5 b b . . 
        . . . . . . c c c c c b b . . . 
        `, SpriteKind.Player)
    Duck.setPosition(61, 93)
    Stingray = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..........fffffffffffff.........
        .......fffbbbbbbbbbbbbbf........
        ......fbbbbbbbbbbbbbbbbf........
        .....fbbbbbbbbbbbb1fbbbbf.......
        .....fbbbbbbbbbbbbbbbbbbbf......
        ......fbbbbbbbbbbbbbbbbbbf......
        .......fbbbbbbbbbbbbbbfbbf......
        ........fbbbbbbbbbbbbb1bbbf.....
        .........fbbbbbbbbbbbbbbbbf.....
        .........ffbbbbbbbbbbbbbbbf.....
        ...........fbbbbbbbbbbbbbbf.....
        ...........fcbbbbbbbbbbbbbf.....
        ..........fcccbbbbbbbbbbbbf.....
        .........fccccbbbbbbbbbbbbf.....
        ........fcccfffbbbbbbbbbbbf.....
        .......fcccf..fffbbbbbbbbbf.....
        ......fcccf......fffbbbbbbf.....
        .....fcccf..........fbbbbbf.....
        .....fccf............fffff......
        ......ff........................
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.Player)
    Stingray.setPosition(87, 79)
    Spider = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . f . . . . . . . . . . . . f . 
        f . f . . . . . . . . . . f . f 
        . . . f . . f f f f . . f . . . 
        . . . . f f f f f f f f . . . . 
        . . f . . f f f 2 f f . . f . . 
        . f . f f f f 2 f f f f f . f . 
        f . . . . f f f f f f . . . . f 
        . . . . f f f f f f f f . . . . 
        . . f f . . f . . f . . f f . . 
        . f . . . . f . . f . . . . f . 
        . f . . . f . . . . f . . . f . 
        f . . . . f . . . . f . . . . f 
        . . . . f . . . . . . f . . . . 
        . . . . f . . . . . . f . . . . 
        `, SpriteKind.Player)
    Spider.setPosition(114, 97)
    Crocodile = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        f...............................
        7f..............................
        77f.............................
        777fff...................f......
        777777fff............ff.f7f.....
        777777777f..........f77f777f....
        7777777777ffffffffff7777711..fff
        77777777777777777777711771f..777
        f777777777777777777771f77777f7f7
        .f777777777777777777777777777771
        ..ff7777777777777777777777712122
        ....f777777777777777777771222227
        .....ff77777777777777777222277ff
        ......f777777777777777777777ff..
        .....f7777fffffff777777fffff....
        .....f777f......ff777777f.......
        .....f7777fff....f7777777fff....
        ......f77777f.....ffff77777f....
        .......fffff..........fffff.....
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.Player)
    Crocodile.setPosition(118, 72)
    Hippo = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        .......ff........ff.............
        ......fddffffffffddf............
        ......fddddddddddddf............
        .......fddddddddddf.............
        .....fffdf1dddf1ddf.............
        ....fddddddddddddddf........f...
        ...fddfdddfdddddddddfffff..fdf..
        ...fdddddddddddddddddddddffdf...
        ...fdddddddddddddddddddddddf....
        ...fbddddddddbdddddddddddddf....
        ...fbbbbdddbbbddddddddddddddf...
        ....fddbbbbbddddddddddddddddf...
        .....fddddddddddddddddddddddf...
        ......fffffdddddddddddddddddf...
        ..........fddddddffffdddddddf...
        ..........fdddddf....fddddddf...
        ..........fdddddf....fdddddf....
        ..........fdddddf....fdddddf....
        ...........fffff......fffff.....
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.Player)
    Hippo.setPosition(141, 99)
    tiger = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ........fff.........fff.........
        .......f111f.44444.f111f........
        ......f11114444444441111f.......
        ......f11144ff444ff44111f.......
        .......fff4f4444444f4fff........
        .........4444ff4ff4444..........
        ........4444f44444f4444.........
        ........fff444444444fff.........
        ........444444444444444.........
        ........ff444f444f444ff.........
        ........111444444444111.........
        .........11141fff14111..........
        ...........1111f1111............
        .............11111..............
        ..............444.....1.........
        .............41114..44f.........
        .............4f1f4..f...........
        ............f4f1f4f44...........
        ............4414144.............
        ................................
        ................................
        `, SpriteKind.Player)
    tiger.setPosition(64, 62)
    game.showLongText("Welcome to Animal Akinator. To start, think of an animal out of the list below, but don't tell me!", DialogLayout.Top)
}
let tiger: Sprite = null
let Hippo: Sprite = null
let Crocodile: Sprite = null
let Spider: Sprite = null
let Stingray: Sprite = null
let Duck: Sprite = null
let Monkey: Sprite = null
let Vulture: Sprite = null
firstScreen()
